services:
  - type: web
    name: lingualens
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: GEMINI_API_KEY
        fromSecret: true
